name: ubuntu

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test-linux:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.6", "2.5"]

    steps:
      - uses: actions/checkout@master
      - name: Setup Ruby Version
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: "x64"

      - name: Setup Dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run Test Suite
        run: |
          bundle exec rake
